"""Regenerate SynthCAD's raster, Windows and embedded icon assets.
Requires Pillow; not needed for a normal CMake build.
"""
from pathlib import Path
from PIL import Image, ImageDraw
root = Path(__file__).resolve().parents[1] / 'viewer' / 'resources'
root.mkdir(exist_ok=True)
# The editable SVG is the source of truth. Its simple rect/polygon vocabulary
# deliberately keeps raster generation independent of browser/Cairo installs.
import xml.etree.ElementTree as ET
large = Image.new('RGBA',(1024,1024));draw=ImageDraw.Draw(large)
for element in ET.parse(root/'synthcad.svg').getroot():
    attrs=element.attrib;tag=element.tag.rsplit('}',1)[-1]
    if tag=='rect':
        x,y,w,h=(float(attrs[k])*16 for k in ['x','y','width','height'])
        draw.rounded_rectangle((x,y,x+w,y+h),float(attrs.get('rx',0))*16,fill=attrs['fill'])
    elif tag=='polygon':
        points=[tuple(float(v)*16 for v in pair.split(',')) for pair in attrs['points'].split()]
        draw.polygon(points,fill=attrs['fill'])
    else:
        raise ValueError(f'Unsupported SVG element: {tag}')
sizes=[16,24,32,48,64,128,256]
for size in sizes:large.resize((size,size),Image.Resampling.LANCZOS).save(root/f'synthcad-{size}.png')
large.resize((256,256),Image.Resampling.LANCZOS).save(root/'synthcad.ico',sizes=[(n,n) for n in sizes])
blob=(root/'synthcad-256.png').read_bytes()
lines=[','.join(str(n) for n in blob[i:i+24]) for i in range(0,len(blob),24)]
(root/'icon_data.h').write_text('#pragma once\n// Generated by scripts/generate-icons.py.\ninline constexpr unsigned char kSynthCadIconPng[]={\n'+',\n'.join(lines)+'\n};\n')
