# Invoked at configure time. Sources are also configure dependencies, so edits
# regenerate the header automatically. Runtime never reads checkout files.
function(synthcad_embed_agent_guides output)
  set(sources "${PROJECT_SOURCE_DIR}/API.md" "${PROJECT_SOURCE_DIR}/docs/agent-cli.md"
      "${PROJECT_SOURCE_DIR}/docs/agent-contract.md" "${PROJECT_SOURCE_DIR}/docs/design-graph.md"
      "${PROJECT_SOURCE_DIR}/skills/synthcad-design/SKILL.md")
  file(GLOB guides CONFIGURE_DEPENDS "${PROJECT_SOURCE_DIR}/docs/guides/*.md")
  list(SORT guides)
  list(APPEND sources ${guides})
  set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS ${sources})
  set(header "#pragma once\nnamespace synthcad { namespace bundled {\nstruct Asset { const char* topic; const char* title; const char* source; const char* content; };\ninline constexpr Asset kAssets[] = {\n")
  foreach(source IN LISTS sources)
    file(READ "${source}" content)
    file(RELATIVE_PATH relative "${PROJECT_SOURCE_DIR}" "${source}")
    get_filename_component(topic "${source}" NAME_WE)
    if(relative STREQUAL "API.md")
      set(topic "api")
    elseif(relative STREQUAL "docs/agent-cli.md")
      set(topic "cli")
    elseif(relative STREQUAL "docs/agent-contract.md")
      set(topic "projects")
    elseif(relative STREQUAL "docs/design-graph.md")
      set(topic "design")
    elseif(relative STREQUAL "skills/synthcad-design/SKILL.md")
      set(topic "skill")
    endif()
    string(REGEX MATCH "(^|\n)#[ \t]+([^\r\n]+)" heading "${content}")
    set(title "${CMAKE_MATCH_2}")
    if(title STREQUAL "")
      set(title "${topic}")
    endif()
    # A fixed raw delimiter is safe only if absent from the source.
    string(FIND "${content}" ")SCGUIDE\"" delimiter_position)
    if(NOT delimiter_position EQUAL -1)
      message(FATAL_ERROR "Guide contains reserved raw-string delimiter: ${relative}")
    endif()
    string(REPLACE "\\" "\\\\" title "${title}")
    string(REPLACE "\"" "\\\"" title "${title}")
    # MSVC limits each raw string literal to about 16 KiB. Adjacent literals
    # concatenate without changing the embedded bytes. Prefer newline cuts;
    # for a long line, move the byte cut back to a UTF-8 codepoint boundary.
    set(literals "")
    set(remaining "${content}")
    string(LENGTH "${remaining}" remaining_length)
    while(remaining_length GREATER 8192)
      string(SUBSTRING "${remaining}" 0 8192 candidate)
      string(FIND "${candidate}" "\n" newline_position REVERSE)
      if(newline_position GREATER_EQUAL 0)
        math(EXPR chunk_length "${newline_position} + 1")
      else()
        set(chunk_length 8192)
        string(SUBSTRING "${remaining}" ${chunk_length} 1 next_byte)
        string(HEX "${next_byte}" next_hex)
        while(next_hex MATCHES "^[89ab]")
          math(EXPR chunk_length "${chunk_length} - 1")
          string(SUBSTRING "${remaining}" ${chunk_length} 1 next_byte)
          string(HEX "${next_byte}" next_hex)
        endwhile()
      endif()
      string(SUBSTRING "${remaining}" 0 ${chunk_length} chunk)
      string(APPEND literals "R\"SCGUIDE(${chunk})SCGUIDE\"\n")
      string(SUBSTRING "${remaining}" ${chunk_length} -1 remaining)
      string(LENGTH "${remaining}" remaining_length)
    endwhile()
    string(APPEND literals "R\"SCGUIDE(${remaining})SCGUIDE\"")
    string(APPEND header "{\"${topic}\", \"${title}\", \"${relative}\", ${literals}},\n")
  endforeach()
  string(APPEND header "};\n} }\n")
  # configure_file preserves timestamps when content has not changed.
  file(WRITE "${output}.in" "${header}")
  configure_file("${output}.in" "${output}" COPYONLY)
endfunction()
